#!/usr/bin/env bash
#
# echoval is intended to echo, and then perform, a shell command.
#
# Notably: whitespace in arguments is preserved by appropriate quotation,
# so the user of the helper-script can easily rerun the command by copypasting.
#
# This makes it easier to report "important" (i.e. side-effectful) actions from
# helper scripts. (As opposed to `set -x`, which echoes every single line...)


# Prior art: Python's shlex
# https://github.com/python/cpython/blob/975ac326ffe265e63a103014fd27e9d098fe7548/Lib/shlex.py#L323
# [^\w@%+=:,./-]
# return "'" + s.replace("'", "'\"'\"'") + "'"

first=1
for arg in "$@"; do
  if [[ $first = 0 ]]; then
    printf " "
  else
    first=0
  fi

  if [[ $arg = "" ]]; then
    printf "''"
  elif [[ $arg =~ [^a-zA-Z0-9_@%+=:,./-] ]]; then
    printf "'%s'" "${arg//'/'\"'\"'}"  # replace ' by '"'"'
  else
    printf "$arg"
  fi
done
printf "\n"

"$@"
